### ISSUE TITLE
Siri Remote functions changing

### ISSUE THREAD

**Issue by tnaz** [folivoraAI/BetterTouchTool#1606]
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
after upgrading to high sierra, the functions of the siri remote seem to not register properly all the time. In the VLC app in particular, the fwd and back buttons will often register as only fwd, or only back, or only play/pause. restarting BTT seems to make them work again, but after some time it the issue will come back, forcing me to restart BTT again. 

#### Device information:

Type of Mac: MBP 15" touchbar 2016
macOS version: 10.13
BetterTouchTool version: 2.310

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

<img width="1016" alt="screen shot 2017-10-11 at 2 06 48 am" src="https://user-images.githubusercontent.com/24709284/31424573-f5919c80-ae28-11e7-8e8c-21f068dba651.png">

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment]
Apple has fixed various Siri Remote related issues in macOS 10.13.1 beta, but I'll check if I can reproduce this. Maybe it'll be automatically fixed with the next macOS update.

**Comment by xiaoken** [comment]
Yes, this is almost exactly what is happening on my mac too!
The only different part is the pause/play function. I only have problems with touchpad related ones like left click or right click.
I'm currently on 10.13.1 latest beta, and it's still broken.

**Comment by tnaz** [comment]
i am now also on 10.13.1. still having issues. seemed to doing ok initially after the update, but then the problem did recur, and is just as frequent as it was before.

**Comment by xiaoken** [comment]
It happens when siri remote goes to sleep mode and breaks the connection with mac.
After waking up, siri remote will register the wrong action.

Is my symptom the same as yours?

**Comment by tnaz** [comment]
Yes, the same. There doesn’t seem to be a way to prevent it from going to sleep

**Comment by fifafu** [comment]
Yes there is no way to prevent the sleep, however you should be able to wake up the remote with any button or trackpad click and afterwards it should register everything correctly. Doesn't it work like this for you?

**Comment by tnaz** [comment]
It doesn’t always register correctly for BTT app specifics after waking. It
often changes the function. Restarting BTT fixes it temporarily.

**Comment by tnaz** [comment]
i tested my aluminum remote with legacy support feature. i have noticed that none of the buttons register correctly with what i have them set for. restarting BTT did not correct the problem for the aluminum remote either.

**Comment by fifafu** [comment]
@tnaz the aluminum remote is not related to the siri remote. Please create another issue. (Make sure to update BTT to the latest version and be sure to actually have a Mac with IR receiver. In general the aluminum remote works fine)

**Comment by tnaz** [comment]
@fifafu the reason i was testing the aluminum remote was to see if i can get it to work. previously it did work, now it does not. just as the siri remote does not work properly. i'm using a usb IR adaptor.

**Comment by xiaoken** [comment]
I dunno if this will help, but i started noticing this behavior in between July and August. I think that a BTT update broke the remote since i didn't upgrade my OS.
