### ISSUE TITLE
Bug: Window Switcher showed BTT's preference window 16 times (resolved by BTT quit/reload)

### ISSUE THREAD

**Issue by TheBloke** [folivoraAI/BetterTouchTool#2176]
### Description of bug:

I just activated the Window Switcher All Open Apps (WS), and was surprised to see "BetterTouchTool" listed in it 16 times - I had the BTT preference window open at that time, but instead of appearing once it was duplicated another 15 times.  All other windows appeared to be correct.

Closing the BTT preference window and running WS again removed all entries, but opening BTT preferences again caused it to again appear 16 times on the WS.  This happened both when BTT preferences was on a different monitor/space as where I ran WS, and when it was on the same monitor.

I then quit BTT and re-opened it, and now it only appears once on the WS as expected.  So right now I can't re-create the bug, and don't know exactly what caused it to first happen.  I had had the BTT preference window open a long time (hours) when I first noticed the issue.  But tonight is the first time I've used the WS in a while so I haven't had an opportunity to spot a problem.

I'll update if it happens again.

### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.): 

If it's relevant, I'm triggering Window Switcher All Open Apps from a Magic Trackpad gesture.

### Device information:

Type of Mac: MP 5.1
macOS version: 10.13.3
BetterTouchTool version: 2.350

### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

[Screenshot](https://i.imgur.com/viNIFeP.png).

**Comment by TheBloke** [comment]
OK I got the problem again today.  This time BTT is shown 7 times.  [Screenshot](https://i.imgur.com/wONbKFX.png).

Here's the sequence of events:

- I logged in today at about 12:00, and left the computer on, with my standard foreground apps open
- BTT was running in the background from login as usual, but I didn't have prefs window open
- About 17:00 I came back to the computer, and at 17:30 I tried to open BTT pref window by launching BetterTouchTool.app (which I do with Alfred) - this is often how I open the Prefs window.
- This time, no pref window appeared; I tried twice more.  I don't remember this happening before.
- So instead I clicked on the BTT menu bar and chose Preferences, which gave me the Prefs window
- Given the strangeness with the Prefs window not appearing at first, I thought I'd try the Window Switcher.  And yes, it's behaving strangely again.

Hope this helps.

**Comment by TheBloke** [comment]
Update again:  I just checked the WS and again it's showing multiple BTTs.  This time, nine copies.

Nothing has changed with regard to BTT since I last posted.  Last time I opened WS, it showed BTT once.  Since then I have left the BTT preference window open on another screen, idle.  

I have used a number of BTT gestures in that time of course, but I have not interacted with the BTT prefs window, or run the WS again until now.

Let me know if I can provide some log or debug info - I'm not sure how I would get that.  I checked ~/Library/Application\ Support/BetterTouchTool/Logs/ and I can't see anything related to the WS in there - it just records various info about the Trackpad and gestures.

**Comment by fifafu** [comment]
I think the latest alpha should fix this :-)

**Comment by TheBloke** [comment]
Thanks!  Installing it now.

**Comment by TheBloke** [comment]
Hi Andreas

Unfortunately it's still happening.   I didn't see it last night in the several hours after I installed the 2.352 update.  I checked the WS every hour or so and it was always fine.

But I left my system on overnight, with the BTT Pref window open, and this morning the WS is showing four copies of BTT.

**Comment by TheBloke** [comment]
Issue ssue still exists in 2.354  [Screenshot](https://i.imgur.com/voKr6UW.png)

Trying 2.355 now :)

(To be clear, this is not an important bug for me.  Just reporting it FYI.)

**Comment by fifafu** [comment]
There hasn't been a change to this since 2.353, so no need to test ;-)
I thought it would be filtered out, maybe I have a typo there. Will check soon.
